[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "example_package_jhw"
version = "0.0.1"
authors = [
  { name="JHW", email="josuesay770@gmail.com" },
]
description = "Un paquete de ejemplo"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/JosueSay/packaging_tutorial"